import Head from "next/head";
import dynamic from "next/dynamic";
const Navbar = dynamic(() => import("@/lib/component/Navbar"));
const Skill = dynamic(() => import("@/lib/component/Skill"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />

        <div className="container px-56 pt-20 flex flex-col	">
          <span className="text-transparent text-lg bg-clip-text bg-gradient-to-br from-purple-600 to-blue-500">
            Hi, my name is
          </span>
          <span className="text-8xl text-white mb-5">Sukhjeet Singh.</span>
          <span className="text-4xl text-gray-400">
            I build things for the cross platform.
          </span>
          <span className="text-xl text-gray-400">
            I’m a software engineer specializing in building exceptional digital
            experiences.
          </span>
          <div className="mt-8">
            <button className="relative inline-flex items-center justify-center p-0.5 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800">
              <span className="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                Let's Connect
              </span>
            </button>
          </div>

          <Skill />
        </div>
      </div>
    </>
  );
}
