import Head from "next/head";
import Navbar from "@/lib/component/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <div className="container px-56 pt-20 flex flex-col	">
          <span className="text-transparent text-lg bg-clip-text bg-gradient-to-br from-purple-600 to-blue-500">
            Hi, my name is
          </span>
          <span className="text-8xl text-white mb-5">Sukhjeet Singh.</span>
          <span className="text-4xl text-gray-400">I build things for the cross platform.</span>
        </div>
      </div>
    </>
  );
}
